# fatigue_data.py
"""
Data loading + preprocessing utilities for the Fatigue Scorer.

What this module does:
- Loads fatigue_training_data.csv
- Parses timestamps, computes duration/rest
- Engineers core features (weekend, start hour, consecutive days lag)
- Computes a rules-based fatigue_index in [0,1] (pseudo-label)
- Builds fixed-length LSTM sequences (window = 14) INCLUDING the target shift as the last timestep

This keeps data work separate so fatigue_scorer.py can focus on modeling.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
import pandas as pd


# ----------------------------
# Configuration / constants
# ----------------------------

FATIGUE_WEIGHTS = {
    "rest": 0.40,
    "consec": 0.25,
    "night": 0.20,
    "hours7d": 0.10,
    "weekend": 0.03,
    "shift": 0.02,
}


@dataclass
class PreparedFatigueData:
    df: pd.DataFrame
    X: np.ndarray
    y: np.ndarray
    meta: pd.DataFrame
    feature_names: List[str]
    numeric_feature_indices: List[int]  # indices in feature_names that should be standardized


# ----------------------------
# Utility helpers
# ----------------------------

def _clip01(x: pd.Series | np.ndarray) -> pd.Series | np.ndarray:
    return np.clip(x, 0.0, 1.0)


def _normalize_shift_type(s: str) -> str:
    s = str(s).strip().lower()
    if s in ("night", "nights"):
        return "night"
    if s in ("evening", "eve"):
        return "evening"
    return "day"

def rolling_sum_past_by_time(group: pd.DataFrame, value_col: str, window: str) -> pd.Series:
    """
    Time-based rolling sum over a lookback window (e.g., "7D", "14D") using start_utc as time.

    IMPORTANT: This intentionally excludes the current shift to avoid trivial leakage.
    It does so by shifting `value_col` by 1 inside each employee group.

    Returns a Series aligned to the *original* group index (so it can be assigned back to the
    parent DataFrame without duplicate-index issues).
    """
    g = group.sort_values("start_utc")
    past = g[value_col].shift(1).fillna(0.0)

    # Rolling over a DatetimeIndex (14D / 7D) is the simplest for time-aware windows.
    rolled = (
        pd.Series(past.values, index=g["start_utc"])
        .rolling(window)
        .sum()
        .astype(float)
        .values
    )

    # Align back to the original group rows (original DataFrame index).
    out = pd.Series(rolled, index=g.index)
    return out.reindex(group.index)


# ----------------------------
# Load + preprocess
# ----------------------------

def load_fatigue_csv(csv_path: str) -> pd.DataFrame:
    """
    Loads the fatigue training CSV.

    For this project, the source CSV is generated by our pipeline and already uses the
    canonical column names (e.g., employee_id/start_utc/end_utc). Because of that, we
    don't need extra aliasing/normalization at this point.
    """
    return pd.read_csv(csv_path)


def engineer_shift_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Parses datetimes, computes:
    - shift_type (normalized)
    - duration_hours
    - rest_hours (time since previous shift end for that employee)
    - start_hour
    - is_weekend
    - consecutive_days_lag (uses previous day's streak to avoid trivial leakage)
    - weekend_shifts_last_14d (rolling count over prior 14 days)
    - night_shifts_last_14d (rolling count over prior 14 days)

    Notes:
    - rest_hours is computed as (current_start - prev_end). This is "pre-shift rest".
    - rolling counts use ONLY past shifts (shifted by 1).
    """
    out = df.copy()

    # Parse timestamps (CSV always contains valid UTC ISO timestamps)
    out["start_utc"] = pd.to_datetime(out["start_utc"], utc=True)
    out["end_utc"] = pd.to_datetime(out["end_utc"], utc=True)

    # shift_type (present in source CSV)
    out["shift_type"] = out["shift_type"].apply(_normalize_shift_type)

    # duration_hours (present and complete in source CSV)
    out["duration_hours"] = pd.to_numeric(out["duration_hours"], errors="raise").astype(float)

    # Basic time features
    # Prefer local hour/weekend flags from the CSV (more semantically correct than UTC-derived).
    out["start_hour"] = pd.to_numeric(out["start_hour_local"], errors="raise").astype(int)
    out["is_weekend"] = out["is_weekend"].astype(int)

    # Sort per employee for time-derived features
    out = out.sort_values(["employee_id", "start_utc"]).reset_index(drop=True)

    # rest_hours: present in the source CSV
    # (We keep a minimal numeric cast to ensure downstream math is stable.)
    out["rest_hours"] = pd.to_numeric(out["rest_hours"], errors="raise").astype(float)

    # consecutive_days is present in the source CSV; keep it and create a lagged version
    out["consecutive_days"] = pd.to_numeric(out["consecutive_days"], errors="raise").astype(float)
    out["consecutive_days_lag"] = (
        out.groupby("employee_id")["consecutive_days"].shift(1).fillna(1.0).astype(float)
    )

    # Rolling counts over the last 14 days (using past shifts only)
    # NOTE: Even though the CSV contains *_last_14d columns, they include the current shift.
    # We recompute as "past-only" to avoid leakage into fatigue_index and LSTM.
    out["night_flag"] = (out["shift_type"] == "night").astype(int)

    # Rolling counts over the last 14 days (past-only) — robust across pandas versions
    out["weekend_shifts_last_14d"] = 0.0
    out["night_shifts_last_14d"] = 0.0

    for emp_id, g in out.groupby("employee_id", sort=False):
        out.loc[g.index, "weekend_shifts_last_14d"] = rolling_sum_past_by_time(g, "is_weekend", "14D").astype(float).values
        out.loc[g.index, "night_shifts_last_14d"] = rolling_sum_past_by_time(g, "night_flag", "14D").astype(float).values

    # Hours worked in the last 7 days (past-only)
    out = add_hours_last_7d(out)

    # One-hot shift type (needed by build_sequences)
    out["shift_day"] = (out["shift_type"] == "day").astype(int)
    out["shift_evening"] = (out["shift_type"] == "evening").astype(int)
    out["shift_night"] = (out["shift_type"] == "night").astype(int)

    out = out.drop(columns=["night_flag"], errors="ignore")
    return out


def add_hours_last_7d(df: pd.DataFrame) -> pd.DataFrame:
    """
    (Re)computes hours_worked_last_7d as a *past-only* time-based rolling sum.

    Why we always recompute (even if the CSV already has a column):
    - The exported CSV typically includes the current shift in hours_worked_last_7d (i.e., a
      cumulative "up to and including this shift" metric).
    - For fatigue scoring we want the load *before* the current shift to avoid leakage.

    Definition:
      hours_worked_last_7d[i] = sum(duration_hours for shifts in the previous 7 days, excluding i)
    """
    out = df.copy()

    # Ensure stable ordering for time-based rolling windows
    out = out.sort_values(["employee_id", "start_utc"]).reset_index(drop=True)

    out["hours_worked_last_7d"] = 0.0
    for emp_id, g in out.groupby("employee_id", sort=False):
        out.loc[g.index, "hours_worked_last_7d"] = rolling_sum_past_by_time(g, "duration_hours", "7D").astype(float).values

    return out


# ----------------------------
# Fatigue index (rules baseline)
# ----------------------------

def compute_fatigue_index(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes a rules-based fatigue_index in [0,1] and component penalties.

    IMPORTANT: This is a pseudo-label (baseline).

    Assumptions for this project:
    - engineer_shift_features() runs before this function and creates:
      rest_hours, consecutive_days_lag, night_shifts_last_14d, weekend_shifts_last_14d,
      hours_worked_last_7d, shift_type.
    """
    out = df.copy()

    # Ensure our leakage-safe hours feature is present (engineer_shift_features already calls it,
    # but this keeps the function usable standalone).
    out = add_hours_last_7d(out)

    # Component penalties in [0,1]
    # a) Rest: penalize short rest (<= 10h is high penalty, >= 16h is low)
    rest = out["rest_hours"].fillna(16.0).astype(float)
    rest_pen = _clip01((16.0 - rest) / (16.0 - 10.0))

    # b) Consecutive days: penalize long streaks (>= 6 starts increasing)
    consec = out["consecutive_days_lag"].fillna(1.0).astype(float)
    consec_pen = _clip01((consec - 5.0) / (9.0 - 5.0))

    # c) Night burden: more nights in last 14 days increases penalty
    night14 = out["night_shifts_last_14d"].fillna(0.0).astype(float)
    night_pen = _clip01(night14 / 6.0)  # 6 nights in 14d ~ max penalty

    # d) Hours burden: more hours in last 7 days increases penalty
    hours7 = out["hours_worked_last_7d"].fillna(0.0).astype(float)
    hours_pen = _clip01((hours7 - 32.0) / (60.0 - 32.0))

    # e) Weekend burden
    wk14 = out["weekend_shifts_last_14d"].fillna(0.0).astype(float)
    weekend_pen = _clip01(wk14 / 4.0)

    # f) Shift type penalty (small nudge)
    shift_pen = out["shift_type"].map({"day": 0.0, "evening": 0.2, "night": 0.5}).fillna(0.0).astype(float)

    # Weighted sum
    fatigue = (
        FATIGUE_WEIGHTS["rest"] * rest_pen
        + FATIGUE_WEIGHTS["consec"] * consec_pen
        + FATIGUE_WEIGHTS["night"] * night_pen
        + FATIGUE_WEIGHTS["hours7d"] * hours_pen
        + FATIGUE_WEIGHTS["weekend"] * weekend_pen
        + FATIGUE_WEIGHTS["shift"] * shift_pen
    )

    out["rest_penalty"] = rest_pen
    out["consec_penalty"] = consec_pen
    out["night_penalty"] = night_pen
    out["hours7d_penalty"] = hours_pen
    out["weekend_penalty"] = weekend_pen
    out["shift_penalty"] = shift_pen

    out["fatigue_index"] = _clip01(fatigue).astype(float)
    return out


# ----------------------------
# Build sequences for LSTM
# ----------------------------

def build_sequences(
    df: pd.DataFrame,
    window: int = 14,
) -> Tuple[np.ndarray, np.ndarray, pd.DataFrame, List[str], List[int]]:
    """
    Builds LSTM sequences INCLUDING the current/target shift as the last timestep.

    For shift i (the target):
      X = shifts [i-window+1 ... i] (inclusive)
      y = fatigue_index at shift i

    Returns:
      X: (N, window, F)
      y: (N,)
      meta: DataFrame with employee_id/start_utc/end_utc/shift_type/fatigue_index
      feature_names: list of per-timestep feature names (length F)
      numeric_feature_indices: which features should be standardized
    """
    # Per-timestep features (simple and interpretable)
    base_cols = [
        "duration_hours",
        "rest_hours",
        "consecutive_days_lag",
        "start_hour",
        "is_weekend",
    ]
    onehot_cols = ["shift_day", "shift_evening", "shift_night"]

    feature_names = base_cols + onehot_cols

    # Numeric indices for scaling (do not scale one-hot)
    numeric_feature_indices = [0, 1, 2, 3]  # duration, rest, consec_lag, start_hour
    # is_weekend is binary; you can scale it too, but it's fine as 0/1.

    X_list: List[np.ndarray] = []
    y_list: List[float] = []
    meta_rows: List[dict] = []

    for emp_id, g in df.groupby("employee_id"):
        g = g.sort_values("start_utc").reset_index(drop=True)

        if len(g) < window:
            continue

        feats = g[feature_names].to_numpy(dtype=np.float32)

        for i in range(window - 1, len(g)):
            X_list.append(feats[i - window + 1 : i + 1])
            y_list.append(float(g.iloc[i]["fatigue_index"]))

            meta_rows.append({
                "employee_id": emp_id,
                "start_utc": g.iloc[i]["start_utc"],
                "end_utc": g.iloc[i]["end_utc"],
                "shift_type": g.iloc[i]["shift_type"],
                "fatigue_index": float(g.iloc[i]["fatigue_index"]),
            })

    X = np.stack(X_list, axis=0) if X_list else np.empty((0, window, len(feature_names)), dtype=np.float32)
    y = np.array(y_list, dtype=np.float32)
    meta = pd.DataFrame(meta_rows)

    return X, y, meta, feature_names, numeric_feature_indices


# ----------------------------
# High-level convenience
# ----------------------------

def prepare_fatigue_data(csv_path: str, window: int = 14) -> PreparedFatigueData:
    """
    Full pipeline:
    - Load CSV
    - Engineer features
    - Compute fatigue_index (pseudo-label)
    - Build sequences for LSTM
    """
    df = load_fatigue_csv(csv_path)

    df = engineer_shift_features(df)
    df = compute_fatigue_index(df)

    X, y, meta, feature_names, numeric_idx = build_sequences(df, window=window)

    return PreparedFatigueData(
        df=df,
        X=X,
        y=y,
        meta=meta,
        feature_names=feature_names,
        numeric_feature_indices=numeric_idx,
    )
